version: '3'
services:
  mdv_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 8181:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mdv-seeds
      MYSQL_USER: mdv-seeds-owner
      MYSQL_PASSWORD: mdv-seeds-owner